language: python

services:
  - mysql

python:
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'CREATE DATABASE kraven;'
  - cp .env.example .env
  - python manage.py kraven update_env DB_HOST=127.0.0.1
  - python manage.py kraven update_env DB_PORT=3306
  - python manage.py kraven update_env DB_DATABASE=kraven
  - python manage.py kraven update_env DB_USERNAME=root
  - python manage.py kraven update_env DB_PASSWORD=
  - python manage.py kraven update_app_key
  - python manage.py kraven update_env DB_CONNECTION=mysql
  - pip install coverage

# command to run tests
script:
  - python manage.py test
  - coverage run --source='.' manage.py test app
  - coverage report -m